#ifndef CUSTOM_VARIANT

#include "variant.h"

 const PinDescription g_APinDescription[]=
{
	// 0..25 - Digital pins
	// ----------------------
	// 0..10 - ESP GPIO
	{ PIO_GPIO, 25, PIO_DIGITAL }, // ESP GPIO25
	{ PIO_GPIO, 27, PIO_DIGITAL }, // ESP GPIO27
	{ PIO_GPIO, 32, PIO_DIGITAL }, // ESP GPIO32
	{ PIO_GPIO, 26, PIO_DIGITAL }, // ESP GPIO26
	{ PIO_GPIO, 33, PIO_DIGITAL }, // ESP GPIO33
	{ PIO_GPIO, 1, PIO_DIGITAL },  // ESP ESP_TXD
	{ PIO_GPIO, 3, PIO_DIGITAL },  // ESP ESP_RXD
	{ PIO_GPIO, 35, PIO_DIGITAL }, // ESP GPIO35
	{ PIO_GPIO, 34, PIO_DIGITAL }, // ESP GPIO34
	{ PIO_GPIO, 4, PIO_DIGITAL },  // ESP GPIO4
	{ PIO_GPIO, 2, PIO_DIGITAL },  // ESP GPIO2
	
	// 11..15 - SAMD GPIO
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, 
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	
	// 16..25 - SAMD GPIO
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },
	
	// 26..31 - SAMD Analog pins
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },	// ADC/AIN[10]
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },	// ADC/AIN[5]
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },	// ADC/AIN[4]
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },	// ADC/AIN[3]
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },	// ADC/AIN[2]
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL },	// ADC/AIN[0]

	// 32..37 - ESP GPIO
	{ PIO_GPIO, 15, PIO_DIGITAL }, // ESP MTDO
	{ PIO_GPIO, 13, PIO_DIGITAL }, // ESP MTCK
	{ PIO_GPIO, 12, PIO_DIGITAL }, // ESP MTDI
	{ PIO_GPIO, 14, PIO_DIGITAL }, // ESP MTMS
	{ PIO_GPIO, 16, PIO_DIGITAL }, // ESP GPIO16
	{ PIO_GPIO, 17, PIO_DIGITAL }, // ESP GPIO17
	
	// end Arduino pinout
	
	// 38..42 - ESP SPI
	{ PIO_GPIO, 19, PIO_DIGITAL }, // ESP MISO
	{ PIO_GPIO, 23, PIO_DIGITAL }, // ESP MOSI
	{ PIO_GPIO, 18, PIO_DIGITAL }, // ESP SCK
	{ PIO_GPIO, 5, PIO_DIGITAL },  // ESP CS
	{ PIO_GPIO, 22, PIO_DIGITAL }, // ESP SR
	
	// 43..44 HAL sensor pins
	{ PIO_GPIO, 36, PIO_DIGITAL },
	{ PIO_GPIO, 39, PIO_DIGITAL },
	
	// 45 SAMD reset
	{ PIO_GPIO, 21, PIO_DIGITAL },

	// 46 ESP_BOOT
	{ PIO_GPIO, 0, PIO_INPUT },

	// 47..51
	{ PIO_NOT_A_PORT, 0, PIO_NOT_A_PIN },
	{ PIO_NOT_A_PORT, 0, PIO_NOT_A_PIN },
	{ PIO_NOT_A_PORT, 0, PIO_NOT_A_PIN },
	{ PIO_NOT_A_PORT, 0, PIO_NOT_A_PIN },
	{ PIO_NOT_A_PORT, 0, PIO_NOT_A_PIN },

	// 52..72 Additional analog
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PB2  - PIN 17
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PB3  - PIN 18
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PB8  - PIN 19
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PB9  - PIN 20
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PA11 - PIN 25
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PA10 - PIN 13
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PA9  - PIN 14
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }, // SAMD PA8  - PIN 15
	{ PIO_GPIO, 32, PIO_DIGITAL }, // ESP GPIO32 - PIN 2
	{ PIO_GPIO, 33, PIO_DIGITAL }, // ESP GPIO33 - PIN 4
	{ PIO_GPIO, 35, PIO_DIGITAL }, // ESP GPIO35 - PIN 7
	{ PIO_GPIO, 34, PIO_DIGITAL }, // ESP GPIO34 - PIN 8
	// pins below can be used as analog only with WiFi disabled
	{ PIO_GPIO, 25, PIO_DIGITAL }, // ESP GPIO25 - PIN 0
	{ PIO_GPIO, 27, PIO_DIGITAL }, // ESP GPIO27 - PIN 1
	{ PIO_GPIO, 26, PIO_DIGITAL }, // ESP GPIO26 - PIN 3
	{ PIO_GPIO, 4, PIO_DIGITAL },  // ESP GPIO4  - PIN 9
	{ PIO_GPIO, 2, PIO_DIGITAL },  // ESP GPIO2  - PIN 10
	{ PIO_GPIO, 15, PIO_DIGITAL }, // ESP GPIO15 - PIN 32
	{ PIO_GPIO, 13, PIO_DIGITAL }, // ESP GPIO13 - PIN 33
	{ PIO_GPIO, 12, PIO_DIGITAL }, // ESP GPIO12 - PIN 34
	{ PIO_GPIO, 14, PIO_DIGITAL }, // ESP GPIO14 - PIN 35

#ifdef BRIKI_ABC
	// 73
	{ PIO_NOT_A_PORT, 0, PIO_NOT_A_PIN },
	// 74 - BUILTIN LED (connected to SAMD)
	{ PIO_NOT_A_PORT, 0, PIO_EXTERNAL }
#endif
};

#endif // CUSTOM_VARIANT